name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run semgrep
        run: semgrep --config default-rules.yml
  dockerfile-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run hadolint
        run: hadolint --config default-rules.yml
  super-calculator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run SuperCalculator
        run: SuperCalculator 3
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run super-linter
        run: super-linter
    
