on:
  push:
    branches:
      - '*'
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go 1.17
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install golang-1.17
          export PATH="/usr/lib/go-1.17/bin:$PATH"
      - name: Run unit tests on Go 1.17
        run: go test ./...
      - name: Install Go 1.18
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install golang-1.18
          export PATH="/usr/lib/go-1.18/bin:$PATH"
      - name: Run unit tests on Go 1.18
        run: go test ./...
      - name: Install Go 1.19
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install golang-1.19
          export PATH="/usr/lib/go-1.19/bin:$PATH"
      - name: Run unit tests on Go 1.19
        run: go test ./...
